### ISSUE TITLE
MISSING/WRONG RECIPE (SUBMIT HERE)

### ISSUE THREAD

**Issue by igentuman** [igentuman/NuclearCraft-Neoteric#29]
This issue for all missing or incorrect recipes. Post in a comments

**Comment by ACTrigger42** [comment]
Isotope Separator Recipe :
10 Lithium Dust to 9 Lithium-7 and 1 Lithium-6
Both products are somewhat radioactive despite both Isotopes being stable IRL.

**Comment by igentuman** [comment]
@ACTrigger42 i've changed the way of getting these isotopes.
Inspired by this
https://patents.google.com/patent/RU2524686C2/en

**Comment by Patman0021** [comment]
Acuq Regia should be [Aqua Regia](https://en.wikipedia.org/wiki/Aqua_regia), unless you were naming it as something different.

**Comment by Patman0021** [comment]
Looks like you can melt gold in the melter, but cannot turn it back into ingots in the ingot former.

**Comment by Ceifeire** [comment]
The active heat sink doesnt have a recipe and crashes the game if placed in creative.

**Comment by Patman0021** [comment]
Carbon Manganese looks like its missing (unless I just cant figure out how to make it)

**Comment by Ceifeire** [comment]
Magnesium Diboride has a recipe that says 1 magnesium + 2 boron = 3 magnesium diboride in the alloy smelter. But in reality it seems to depend on the order you load them in. Whichever ingot is in the right slot will burn 2 and the left will burn 1. you will still get 3 magnesium diboride

**Comment by Knorke75** [comment]
I could not find a way to make Niobium (except from the dust, which can only be made from the Ingot again).
Same thing with Titanium.

Also there is no recipe for Niobium Tin Ingot and Niobium Titanium Ingot.

**Comment by Knorke75** [comment]
You cannot make any BSCCO related blocks

**Comment by Knorke75** [comment]
You cannot make Beryllium yet

**Comment by igentuman** [comment]
you can make beryllium. all recipes there.

**Comment by igentuman** [comment]
all mentioned problems until now have been fixed

**Comment by DevDyna** [comment]
missing recipe for chlorine (i'm still try pressing 'R' key on this screen but dont show it ; same for _flowing version)
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/78147916/47c8f282-a848-4626-bb75-ab9b110d3543)

**Comment by DevDyna** [comment]
missing recipe on ingot former for `nuclearcraft:copper` , `nuclearcraft:iron` and `nuclearcraft:gold` (from melting on melter raw ores)

**Comment by nohax955** [comment]
u cant make the milk chocolate bars
nor the marshmallows
the fluid exists and can be made
but you cant use that fluid for anything
the solidifying recipes for the fluids dont work or dont exist
missing recipe on ingot former :
nuclearcraft:milk_chocolate -> nuclearcraft:milk_chocolate
nuclearcraft:melted_marshmallow -> nuclearcraft:marshmallow

**Comment by igentuman** [comment]
This already fixed for 1.18

**Comment by nohax955** [comment]
and the rest?

**Comment by nohax955** [comment]
energy upgrades dont work in 1.18.2

**Comment by FittingCanvas** [comment]
List of every material that has NO recipe/unobtainable in the latest release version for 1.19.2 according to Just Enough Items, excluding the hundreds of fuels and isotopes:
Analyzer, Glowing Mushroom, Portal, Supercold Ice Block, all HEV items, Silicon Gem, Sic Fiber, Salt, Sawdust, Dominos, every "Za" version of fuel

The list, but ingots (excluding Dust <---> Ingot <---> Plate <---> molten recursive recipes):
Niobium Tin, Tungsten, Yttrium, ~~Palladium,~~ Tungsten Carbide, Sodium, Niobium Titanium, Titanium, Super Alloy, Aluminum, Sic Sic Cmc, Niobium, Strontium, Osmium, Osmiridium, Nichrome, Hafnium

The list, but dusts not obtainable from any recipe, including ingots:
Germanium, Sulfur, Purpur, Alugentum, Samarium, Erbium, Energetic Blend, C Mn Blend, Dimensional Blend, Enderium, Terbium, Quartz

The list, but liquids:
Radon, Low Pressure Steam, Low Quality Steam, Neon, Chlorine, Argon, Redstone Ethanol, Pasteurized Milk, Emergency Coolant/Heated, Aluminum Slurry

**Comment by FittingCanvas** [comment]
Every non-existent recipe whose non-existence is a critical issue:
Sulfur (ensures unobtainability of DU plate and all plates beyond it)
Chlorine (ensures unobtainability of hydrochloric acid)
Analyzer (there's a video of it working on the CurseForge page, yet somehow it isn't craftable?)
QNP charging port (what's the point of a big chunky power tool that doesn't have a battery? Why is Tough Spaxel so much more expensive?)
Quartz Dust (makes Energy Upgrade unobtainable, effectively making machines that can be made somewhat fast at the cost of needing infinite energy per tick)
that's it lol

**Comment by Xplodin** [comment]
```
Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: Nuclearcraft Neoteric nuclearcraft:fission_reactor_controller/americium_hea_242 class igentuman.nc.block.entity.fission.FissionControllerBE$Recipe

java.lang.StringIndexOutOfBoundsException: begin 0, end 1, length 0
	at java.lang.String.checkBoundsBeginEnd(String.java:4606) ~[?:?]
	at java.lang.String.substring(String.java:2709) ~[?:?]
	at igentuman.nc.content.fuel.FuelDef.getHeatBoilingMode(FuelDef.java:78) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%231200!/:1.0.0-beta.6]
	at igentuman.nc.item.ItemFuel.setDefinition(ItemFuel.java:43) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%231200!/:1.0.0-beta.6]
	at igentuman.nc.item.ItemFuel.<init>(ItemFuel.java:32) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%231200!/:1.0.0-beta.6]
	at igentuman.nc.block.entity.fission.FissionControllerBE$Recipe.getFuelItem(FissionControllerBE.java:895) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%231200!/:1.0.0-beta.6]
	at igentuman.nc.block.entity.fission.FissionControllerBE$Recipe.getDepletionTime(FissionControllerBE.java:914) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%231200!/:1.0.0-beta.6]
	at igentuman.nc.compat.jei.FissionCategoryWrapper.setRecipe(FissionCategoryWrapper.java:96) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%231200!/:1.0.0-beta.6]
	at igentuman.nc.compat.jei.FissionCategoryWrapper.setRecipe(FissionCategoryWrapper.java:31) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%231200!/:1.0.0-beta.6]
	at mezz.jei.library.util.IngredientSupplierHelper.getIngredientSupplier(IngredientSupplierHelper.java:22) ~[jei-1.20.1-forge-15.2.0.27.jar%231097!/:15.2.0.27]
	at mezz.jei.library.recipes.RecipeManagerInternal.lambda$addRecipes$0(RecipeManagerInternal.java:120) ~[jei-1.20.1-forge-15.2.0.27.jar%231097!/:15.2.0.27]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:126) ~[jei-1.20.1-forge-15.2.0.27.jar%231097!/:15.2.0.27]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:108) ~[jei-1.20.1-forge-15.2.0.27.jar%231097!/:15.2.0.27]
	at mezz.jei.library.load.registration.RecipeRegistration.addRecipes(RecipeRegistration.java:64) ~[jei-1.20.1-forge-15.2.0.27.jar%231097!/:15.2.0.27]
	at igentuman.nc.compat.jei.JEIPlugin.registerRecipes(JEIPlugin.java:104) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%231200!/:1.0.0-beta.6]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeManager$10(PluginLoader.java:144) ~[jei-1.20.1-forge-15.2.0.27.jar%231097!/:15.2.0.27]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-forge-15.2.0.27.jar%231097!/:15.2.0.27]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:144) ~[jei-1.20.1-forge-15.2.0.27.jar%231097!/:15.2.0.27]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-forge-15.2.0.27.jar%231097!/:15.2.0.27]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.20.1-forge-15.2.0.27.jar%231097!/:15.2.0.27]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.20.1-forge-15.2.0.27.jar%231097!/:15.2.0.27]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451) ~[client-1.20.1-20230612.114412-srg.jar%231408!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.20.1-20230612.114412-srg.jar%231408!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.20.1-20230612.114412-srg.jar%231408!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%231408!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%231408!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%231408!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%231408!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%231408!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%231408!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%231408!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.19.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]

```
also nuclearcraft:fluid_infuser/ice-liquid_helium is giving a barrier

**Comment by tabr** [comment]
[1.20.1] No "Manganese Oxide" recipe
version: NuclearCraft-1.20.1-1.0.0-beta.6 [may, 25]
it seems to be there is should be smelting recipe:
https://ftb.fandom.com/wiki/Manganese_Oxide
[Crushed Rhodochrosite] => [Manganese Oxide Dust]
but there is no recipe in JEI and can't smelt [Crushed Rhodochrosite].

**Comment by igentuman** [comment]
@tabr 
Everything looking good
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/4759881/57e065f1-a87e-4747-a3ab-0f3d63b2fae2)
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/4759881/765bb0c4-2304-402c-bab7-0cf721598a3c)

**Comment by SrNadien** [comment]
add compat industrial foregoing lasser ore drill ores extract please

**Comment by diefesson** [comment]
# Wrong recipe for Uranium 238 Za, using Oxygen

![Captura de tela 2024-11-11 094749](https://github.com/user-attachments/assets/4a7c66b8-7987-4bba-83ba-47ed98360a7a)

# Invalid recipe for Uranium 238 Ox

![Captura de tela 2024-11-11 094731](https://github.com/user-attachments/assets/1b511b36-eb85-4ccf-a6f7-feb34bbdfa59)

# Wrong recipe for Uranium 235 Ox, using Nitrogen

![Captura de tela 2024-11-11 100506](https://github.com/user-attachments/assets/8e47247b-b43b-4ed1-a9d5-4756c239c475)

# Invalid recipe for Uranium 235 Ni

![Captura de tela 2024-11-11 100448](https://github.com/user-attachments/assets/d7addb98-d11b-49a6-b24b-73a1117f0025)

**Comment by Krebkel** [comment]
No Americium-242 recipe.
TBU is crafted only from Thorium-232. Thorium-230 is useless as of now (1.2.0 on 1.20.1)
