### ISSUE TITLE
[BUG] NullPointerException when attempting to join dedicated server

### ISSUE THREAD

**Issue by ImperialsGit** [igentuman/NuclearCraft-Neoteric#32]
Client and server are fresh installs of the mod, no other mods installed. Error is only logged serverside, no visible cause clientside. Likely buffer over/underflow, as when attempting to use with other mods the connection failure screen is very clearly iterating over an unintended memory region.

Pretty standard test environment, only exemplary thing is longPaths has been enabled serverside.

`[09Dec2023 17:12:49.153] [Netty Server IO #2/ERROR] [igentuman.nc.NuclearCraft/]: Error writing recipe to packet.
java.lang.NullPointerException: Cannot invoke "net.minecraftforge.fluids.FluidStack.isEmpty()" because "stack" is null
	at net.minecraftforge.common.extensions.IForgeFriendlyByteBuf.writeFluidStack(IForgeFriendlyByteBuf.java:126) ~[forge-1.19.2-43.3.0-universal.jar%23106!/:?]
	at igentuman.nc.recipes.type.NcRecipe.write(NcRecipe.java:98) ~[NuclearCraft-1.19.2-1.0.0-beta.4.jar%2399!/:1.0.0-beta.4]
	at igentuman.nc.recipes.serializers.NcRecipeSerializer.toNetwork(NcRecipeSerializer.java:188) ~[NuclearCraft-1.19.2-1.0.0-beta.4.jar%2399!/:1.0.0-beta.4]
	at igentuman.nc.recipes.serializers.NcRecipeSerializer.m_6178_(NcRecipeSerializer.java:29) ~[NuclearCraft-1.19.2-1.0.0-beta.4.jar%2399!/:1.0.0-beta.4]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_179469_(ClientboundUpdateRecipesPacket.java:52) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_236828_(FriendlyByteBuf.java:162) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_5779_(ClientboundUpdateRecipesPacket.java:27) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
	at net.minecraftforge.network.filters.VanillaPacketSplitter.appendPackets(VanillaPacketSplitter.java:68) ~[forge-1.19.2-43.3.0-universal.jar%23106!/:?]
	at net.minecraftforge.network.filters.ForgeConnectionNetworkFilter.splitPacket(ForgeConnectionNetworkFilter.java:60) ~[forge-1.19.2-43.3.0-universal.jar%23106!/:?]
	at net.minecraftforge.network.filters.VanillaPacketFilter.encode(VanillaPacketFilter.java:60) ~[forge-1.19.2-43.3.0-universal.jar%23106!/:?]
	at net.minecraftforge.network.filters.VanillaPacketFilter.encode(VanillaPacketFilter.java:23) ~[forge-1.19.2-43.3.0-universal.jar%23106!/:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[netty-codec-4.1.77.Final.jar%2380!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at net.minecraft.network.Connection.m_243087_(Connection.java:209) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
	at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:198) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by igentuman** [comment]
@ImperialsGit try this build
https://github.com/igentuman/NuclearCraft-Neoteric/suites/18905357283/artifacts/1103945659

**Comment by ImperialsGit** [comment]
> @ImperialsGit try this build https://github.com/igentuman/NuclearCraft-Neoteric/suites/18905357283/artifacts/1103945659

![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/68413525/d1d6ba46-031a-4883-9daa-70d3192d53ed)

This is the only actual evidence of any issue visually, even with that build. Nothing in logs of either the server or the client.

**Comment by igentuman** [comment]
ok. i will do local tests

**Comment by igentuman** [comment]
@ImperialsGit https://github.com/igentuman/NuclearCraft-Neoteric/suites/18912040937/artifacts/1104477278
works for me now
