### ISSUE TITLE
NcRecipeSerializer.java returns null on item stack output which is causing kubejs to error out.

### ISSUE THREAD

**Issue by Drackion** [igentuman/NuclearCraft-Neoteric#35]
KubeJS scripts halted due to an unexpected null while scanning for recipe types, which is found in NCRecipeSerializer.java line 71.
https://github.com/igentuman/NuclearCraft-Neoteric/blob/767fbd73116fcb209896722eec2646914a6721b1/src/main/java/igentuman/nc/recipes/serializers/NcRecipeSerializer.java#L71

kjs server log:
https://mclo.gs/iGEI0SR

stack trace:
```
[15:34:16] [ERROR] ! Error in 'ServerEvents.recipes': null
[15:34:16] [ERROR] ! java.lang.NullPointerException
[15:34:16] [ERROR] !   at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[15:34:16] [ERROR] !   at java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[15:34:16] [ERROR] !   at …kubejs.recipe.RecipesEventJS.runInParallel(RecipesEventJS.java:715)
[15:34:16] [ERROR] !   at …kubejs.recipe.RecipesEventJS.forEachRecipeAsync(RecipesEventJS.java:545)
[15:34:16] [ERROR] !   at …kubejs.recipe.RecipesEventJS.remove(RecipesEventJS.java:580)
[15:34:16] [ERROR] !   at java.lang.reflect.Method.invoke(Method.java:568)
[15:34:16] [ERROR] !   at …rhino.MemberBox.invoke(MemberBox.java:160)
[15:34:16] [ERROR] !   at …rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[15:34:16] [ERROR] !   at …rhino.Interpreter.interpretLoop(Interpreter.java:986)
[15:34:16] [ERROR] !   at …rhino.Interpreter.interpret(Interpreter.java:370)
[15:34:16] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[15:34:16] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[15:34:16] [ERROR] !   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[15:34:16] [ERROR] !   at …rhino.NativeArray.iterativeMethod(NativeArray.java:1314)
[15:34:16] [ERROR] !   at …rhino.NativeArray.execIdCall(NativeArray.java:1798)
[15:34:16] [ERROR] !   at …rhino.IdFunctionObject.call(IdFunctionObject.java:103)
[15:34:16] [ERROR] !   at …rhino.Interpreter.interpretLoop(Interpreter.java:986)
[15:34:16] [ERROR] !   at …rhino.Interpreter.interpret(Interpreter.java:370)
[15:34:16] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[15:34:16] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[15:34:16] [ERROR] !   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[15:34:16] [ERROR] !   at …rhino.Interpreter.interpretLoop(Interpreter.java:986)
[15:34:16] [ERROR] !   at …rhino.Interpreter.interpret(Interpreter.java:370)
[15:34:16] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[15:34:16] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[15:34:16] [ERROR] !   at …rhino.Context.doTopCall(Context.java:1307)
[15:34:16] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[15:34:16] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[15:34:16] [ERROR] !   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[15:34:16] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[15:34:16] [ERROR] !   at …rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[15:34:16] [ERROR] !   at …rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[15:34:16] [ERROR] !   at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy93.onEvent(Unknown Source)
[15:34:16] [ERROR] !   at …kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[15:34:16] [ERROR] !   at …kubejs.event.EventHandler.postToHandlers(EventHandler.java:304)
[15:34:16] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:272)
[15:34:16] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:226)
[15:34:16] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:189)
[15:34:16] [ERROR] !   at …kubejs.recipe.RecipesEventJS.post(RecipesEventJS.java:356)
[15:34:16] [ERROR] !   at net.minecraft.world.item.crafting.RecipeManager.handler$zbh000$customRecipesHead(RecipeManager.java:5531)
[15:34:16] [ERROR] !   at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java)
[15:34:16] [ERROR] !   at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34)
[15:34:16] [ERROR] !   at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13)
[15:34:16] [ERROR] !   at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[15:34:16] [ERROR] !   at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[15:34:16] [ERROR] !   at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69)
[15:34:16] [ERROR] !   at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:34:16] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[15:34:16] [ERROR] !   at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[15:34:16] [ERROR] !   at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
[15:34:16] [ERROR] !   at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
[15:34:16] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[15:34:16] [ERROR] !   at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
[15:34:16] [ERROR] !   at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
[15:34:16] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
[15:34:16] [ERROR] !   at net.minecraft.server.MinecraftServer.m_129861_(MinecraftServer.java:1345)
[15:34:16] [ERROR] !   at net.minecraft.server.commands.ReloadCommand.m_138235_(ReloadCommand.java:22)
[15:34:16] [ERROR] !   at net.minecraft.server.commands.ReloadCommand.m_287964_(ReloadCommand.java:53)
[15:34:16] [ERROR] !   at MC-BOOTSTRAP/brigadier@1.1.8/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[15:34:16] [ERROR] !   at net.minecraft.commands.Commands.m_242674_(Commands.java:257)
[15:34:16] [ERROR] !   at net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1246)
[15:34:16] [ERROR] !   at net.minecraft.server.network.ServerGamePacketListenerImpl.m_244885_(ServerGamePacketListenerImpl.java:1223)
[15:34:16] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67)
[15:34:16] [ERROR] !   at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[15:34:16] [ERROR] !   at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:34:16] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[15:34:16] [ERROR] !   at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[15:34:16] [ERROR] !   at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
[15:34:16] [ERROR] !   at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
[15:34:16] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[15:34:16] [ERROR] !   at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
[15:34:16] [ERROR] !   at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
[15:34:16] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115)
[15:34:16] [ERROR] !   at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732)
[15:34:16] [ERROR] !   at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665)
[15:34:16] [ERROR] !   at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
[15:34:16] [ERROR] !   at java.lang.Thread.run(Thread.java:833)
[15:34:16] [ERROR] ! Caused by: java.lang.NullPointerException: ItemStack should never be null, but recipe nuclearcraft:ingot_former/fuel_californium_lecf_251_za[nuclearcraft:ingot_former] returned null as the output!
[15:34:16] [ERROR] !   at …kubejs.recipe.JsonRecipeJS.hasOutput(JsonRecipeJS.java:41)
[15:34:16] [ERROR] !   at …kubejs.recipe.filter.OutputFilter.test(OutputFilter.java:15)
[15:34:16] [ERROR] !   at …kubejs.recipe.filter.OrFilter.test(OrFilter.java:14)
[15:34:16] [ERROR] !   at …kubejs.recipe.RecipesEventJS$RecipeStreamFilter.test(RecipesEventJS.java:494)
[15:34:16] [ERROR] !   at …kubejs.recipe.RecipesEventJS$RecipeStreamFilter.test(RecipesEventJS.java:491)
[15:34:16] [ERROR] !   at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
[15:34:16] [ERROR] !   at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
[15:34:16] [ERROR] !   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[15:34:16] [ERROR] !   at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
[15:34:16] [ERROR] !   at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[15:34:16] [ERROR] !   at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
[15:34:16] [ERROR] !   at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
[15:34:16] [ERROR] !   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[15:34:16] [ERROR] !   at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[15:34:16] [ERROR] !   at …kubejs.recipe.RecipesEventJS.lambda$forEachRecipeAsync$11(RecipesEventJS.java:545)
```

**Comment by Drackion** [comment]
KubeJS isn't able to handle a NULL being thown at it but can easily deal with an empty item stack being returned.

**Comment by igentuman** [comment]
the line you pointing is for recipe object not item stack
i've checked the original recipe, it has proper structure and item is not null

**Comment by igentuman** [comment]
How do i replicate the issue?

**Comment by MommyHeather** [comment]
If it's hitting the line you mentioned, this means you've given an invalid json - which *should* error.

However, the recipe serialiser should be actually throwing that error, rather than returning `null` from a method marked `@NotNull`. In this case, either pass the existing exception up the chain, or throw a new one with your own additional information.
