### ISSUE TITLE
Multiplayer support not working

### ISSUE THREAD

**Issue by MrEizy** [igentuman/NuclearCraft-Neoteric#56]
Caused by: java.lang.IllegalArgumentException: ItemStackIngredients cannot be created using the empty ingredient.
	at igentuman.nc.recipes.ingredient.creator.ItemStackIngredientCreator.from(ItemStackIngredientCreator.java:46) ~[NuclearCraft-1.20.1-1.0.0-beta.1.jar%23852!/:1.0.0-beta.1]
	at igentuman.nc.recipes.ingredient.creator.ItemStackIngredientCreator.read(ItemStackIngredientCreator.java:57) ~[NuclearCraft-1.20.1-1.0.0-beta.1.jar%23852!/:1.0.0-beta.1]
	at igentuman.nc.recipes.ingredient.creator.ItemStackIngredientCreator.read(ItemStackIngredientCreator.java:33) ~[NuclearCraft-1.20.1-1.0.0-beta.1.jar%23852!/:1.0.0-beta.1]
	at igentuman.nc.recipes.serializers.NcRecipeSerializer.fromNetwork(NcRecipeSerializer.java:153) ~[NuclearCraft-1.20.1-1.0.0-beta.1.jar%23852!/:1.0.0-beta.1]
	at igentuman.nc.recipes.serializers.NcRecipeSerializer.m_8005_(NcRecipeSerializer.java:29) ~[NuclearCraft-1.20.1-1.0.0-beta.1.jar%23852!/:1.0.0-beta.1]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_133647_(ClientboundUpdateRecipesPacket.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23972!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_236838_(FriendlyByteBuf.java:211) ~[client-1.20.1-20230612.114412-srg.jar%23972!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_236845_(FriendlyByteBuf.java:227) ~[client-1.20.1-20230612.114412-srg.jar%23972!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.<init>(ClientboundUpdateRecipesPacket.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23972!/:?]
	at net.minecraft.network.ConnectionProtocol$PacketSet.m_178327_(ConnectionProtocol.java:459) ~[client-1.20.1-20230612.114412-srg.jar%23972!/:?]
	at net.minecraft.network.ConnectionProtocol.m_178321_(ConnectionProtocol.java:522) ~[client-1.20.1-20230612.114412-srg.jar%23972!/:?]
	at net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:32) ~[client-1.20.1-20230612.114412-srg.jar%23972!/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	... 89 more

What it says when trying to join a friend with nuclearcraft

**Comment by igentuman** [comment]
This is known issue. It was fixed in 1.19 branch. Waiting to be merged in 1.20
